
package com.the50ft.tree.rules

import com.the50ft.tree.model.Person
import com.the50ft.tree.model.Aircraft
import com.the50ft.tree.model.Checkout
import com.the50ft.tree.model.Requestor

import com.the50ft.tree.rules.DualInstruction

global java.io.PrintStream out
global java.util.List list


rule Available @Unit(DualInstruction.class) when
  $student : /requestor
  $instructor : /persons[this!=$student]
  $aircraft : /aircrafts
  $student_checkout : /checkouts[aircraft==$aircraft && person==$student]
  $instructor_checkout : /checkouts[aircraft==$aircraft && person==$instructor]
then
  System.out.println( $student + "+" + $instructor + " @ " + $aircraft);
  //list.add( $instructor );
end

